// user 1
POST http://localhost:5000/auth/signup 
content-type: application/json


{
    "user_name":"harini_30",
    "password":"Fderb@1234",
    "email":"harighj.gk@gmail.com"
}
###
//verify otp
POST http://localhost:5000/auth/verifyotp
content-type: application/json

{
    "user_id":2,
    "otp":"647242"
}
###

//user 2
POST http://localhost:5000/auth/signup
content-type: application/json


{
    "user_name":"harini",
    "password":"Apple@2341",
    "email":"harinikrishna1230@gmail.com"
}

###

// user 3
POST http://localhost:5000/auth/signup
content-type: application/json


{
    "user_name":"harinikrishana",
    "password":"Apple@2568",
    "email":"harini.g@codingmart.com"
}

###

// resend otp
POST http://localhost:5000/auth/resentotp
content-type: application/json


{
    "resend":true,
    "email":"harini123424.gk@gmail.com"
}

###

//user 4
POST http://localhost:5000/auth/signup
content-type: application/json


{
    "user_name":"inira",
    "password":"harini@12",
    "email":"harini123424.gk@gmail.com"
}

###
//login
POST http://localhost:5000/auth/login


{
    "deviceid":"589658 window",
    "email":"harini123424.gk@gmail.com",
    "password":"Apple@1234"
}

###
//forgot password
POST http://localhost:5000/auth/forgotpassword
content-type: application/json

{
    "email":"harini123424.gk@gmail.com"
}

###
// group
POST http://localhost:5000/group/new
content-type: application/json

{
    "group_name":"Billianera",
    "created_by":1,
   
    "type":"group",
    "simplify":false

}
###
// currency converter
POST http://localhost:5000/auth//account/settings/currconvert
content-type: application/json

{
    "from_currency":"USD",
    "to_currency":"INR",
    "user_id":1
}

###
// create group expense
POST http://localhost:5000/group/expense/create
content-type: application/json

{
    "user_id":1,
    "group_id":1,
    "expense_name":"expense7",
    "amount":200,
    "split_type":0,
    "no_group":true,
    "reimbursement":false

}

###
// 
POST http://localhost:5000/expense/create
content-type: application/json

{
    "user_id":1,
    "type":0,
    "split":0,
    "to_id":2,
    "expense_name":"exp1",
    "amount":40,
    "no_group":true

}
###
POST http://localhost:5000/group/expense/delete
content-type: application/json

{
    "group_id":1,
    "expense_id":1,
}

###
POST http://localhost:5000/api/v3.0/blocked_users
content-type: application/json

{
    "user_id":1,
    " black_listed_id":5,
}

###
POST http://localhost:5000/settle
content-type: application/json

{
    "user_id":1,
    "to_id":2,
    "amount":40,
    "no_group":true

}
###
POST http://localhost:5000/auth/account/settings/notify
Content-Type: application/json

{
    "user_id":1,
    "add_to_group":0,
    "add_a_friend":1,
    "expense_added":1,
    "expense_detected":true,
    "expense_due":false,
    "pays_me":false,
    "monthly_summary":false,
    "news_updates":false
}


###
POST http://localhost:5000/expense/getepense
Content-Type: application/json

{
    "group_id":1
}

###
POST http://localhost:5000/group/getgroups
Content-Type: application/json

{
    "user_id":1
}
###
POST http://localhost:8000/signup
Content-Type: application/json

{
    "name":"Harini",
    "email":"harini123424.gk@gmail.com"
}